
enum {
	AIM_RECV_MESG		=	1,
	AIM_BUDDY_ONLINE	=	2, 
	AIM_BUDDY_OFFLINE	=	3, 
	AIM_BUDDY_AWAY		=	4, 
	AIM_BUDDY_UNAWAY	=	5,
	AIM_BUDDY_IDLE		=	6,	
	AIM_BUDDY_MSG_RECV	=   7,
	AIM_CONNECTED		=   8,
	AIM_DISCONNECTED	=	9,
	AIM_READ_MSGS		=   10,
	AIM_BUDDY_INFO		=	11	
};
enum { 
	ACCOUNT_VIEW		=	1,
	ACCOUNT_EDITOR_VIEW	=	2,
	BUDDY_VIEW		=	3,
	CONVERSATION		=   4,
	ABOUT_VIEW		=	5,
	PREF_VIEW		= 6
};
